### ISSUE TITLE
How I change collapse and expand icon?

### ISSUE THREAD

**Issue by EricDosReis** [LukaszWatroba/v-accordion#16]
I want to change collapse and expand icons to arrows. I looked at the CSS and Javascript code and I didn't find it.

**Comment by EricDosReis** [comment]
Yes, now I found in the CSS file, on lines of this code block:

```css
.vAccordion--default v-pane-header::after,
.vAccordion--default v-pane-header::before {
	background: #2196F3;
	content: '';
	display: block;
	height: 1px;
	width: 10px;
	position: absolute;
	top: 50%;
	right: 0;
	-webkit-transform-origin: 50% 50%;
	-ms-transform-origin: 50% 50%;
	transform-origin: 50% 50%;
	transition: all .25s
}
```

The icons are done in pure CSS. Good trick, but, it's bad to find.

Great job in this Angular Component!
