### ISSUE TITLE
How to hide the + / - icons?

### ISSUE THREAD

**Issue by felixfbecker** [LukaszWatroba/v-accordion#31]
I need custom buttons (for editing / deleting) in the place of the + / - icons. I did not find a way to hide them, neither in the CSS nor as an attribute option.

**Comment by kylealwyn** [comment]
@felixfbecker: The +/- buttons are the pseudo-elements of `v-pane-header`

Below is how I overwrote them using a font library, customize as you desire:

``` css
v-pane-header::before {
  content: none;
}

v-pane-header::after {
  content: '\f104';
  font-family: 'Ionicons';
  display: block;
  position: absolute;
  top: calc(50% - 16px);
  left: 1rem;
  font-size: 22px;
  transform-origin: 50% 50%;
  transform: rotate(-90deg);
  transition: all $v-pane-hover-duration;
}
```
