### ISSUE TITLE
Accordion Title Remains Blue after Closing

### ISSUE THREAD

**Issue by SomethingNew71** [LukaszWatroba/v-accordion#46]
Steps to reproduce: 

1. Open accordion item
2. Click on title to close accordion 
3. Note accordion title remains blue despite no longer being active.

Can be duplicated on demo page.

Example:
[http://i.imgur.com/oatZR8q.png](http://i.imgur.com/oatZR8q.png)

**Comment by LukaszWatroba** [comment]
It's there just to indicate which v-pane is currently focused (you can use arrow and spacebar keys to navigate). But you can always change that by overriding the css:

```css
.vAccordion--default v-pane-header:focus {
  color: #212121;
}
```
