### ISSUE TITLE
How to make the v-pane-content scrollable?

### ISSUE THREAD

**Issue by GeorgeChackungal** [LukaszWatroba/v-accordion#87]
How do i make the v-pane-content scroll-able so that when it expands it doesn't increase the height of the container?

**Comment by ravimallya** [comment]
How about adding `max-height` and `overflow-y:auto;` to the `.vAccordion--default v-pane.is-expanded>v-pane-content>div` element like below: 

```css
.vAccordion--default v-pane.is-expanded>v-pane-content>div {
    max-height: 100px;
    overflow-y: scroll /* or auto */;
}
```
