### ISSUE TITLE
How to disable clicking on an accordion heading?

### ISSUE THREAD

**Issue by yugan24** [LukaszWatroba/v-accordion#9]

**Comment by LukaszWatroba** [comment]
You can use the pointer-events css property:

````html
<v-pane-header ng-disabled="pane.isDisabled">
    <h5>{{ pane.header }}</h5>
</v-pane-header>
````

````css
v-pane-header[disabled] {
    pointer-events: none;
}
````
